AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for UserState Lambda that reads/writes users/{userSub}/sidebar.json in S3

Resources:
  UserStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-user-state-bucket'

  UserStateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./aws/user-state/
      Environment:
        Variables:
          BUCKET_NAME: !Ref UserStateBucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::${UserStateBucket}/*
      Events:
        UserStateApi:
          Type: Api
          Properties:
            Path: /user/state
            Method: ANY

Outputs:
  UserStateApiUrl:
    Description: "Invoke URL for the user state API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/state"
